// Package generator turns parser JSON IR into thin executable acceptance test
// entry points, with the metadata the acceptance mutator reads.
package generator

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/unclebob/forgelet-bridge/acceptance/runtime"
)

// MetadataSchemaVersion is the metadata schema this generator writes.
const MetadataSchemaVersion = 1

// Metadata describes one generated feature's entry point.
type Metadata struct {
	SchemaVersion      int      `json:"schema_version"`
	FeaturePath        string   `json:"feature_path"`
	IRPath             string   `json:"ir_path"`
	ImplementationHash string   `json:"implementation_hash"`
	HashScope          string   `json:"hash_scope"`
	GeneratedFiles     []string `json:"generated_files"`
}

// Request names the inputs of one generation run.
type Request struct {
	IRPath      string
	FeaturePath string
	OutputDir   string
	ProjectRoot string
}

// Generate writes the entry point for one feature and returns its metadata.
func Generate(request Request) (Metadata, error) {
	feature, err := runtime.LoadFeature(request.IRPath)
	if err != nil {
		return Metadata{}, err
	}
	if strings.TrimSpace(feature.Name) == "" {
		return Metadata{}, fmt.Errorf("%s: feature has no name", request.IRPath)
	}
	irPath, err := filepath.Abs(request.IRPath)
	if err != nil {
		return Metadata{}, err
	}
	featurePath := request.FeaturePath
	if featurePath == "" {
		featurePath = filepath.Join("features", stem(request.IRPath)+".feature")
	}

	filePath, err := writeEntryPoint(request.OutputDir, feature, featurePath, irPath)
	if err != nil {
		return Metadata{}, err
	}

	metadata, err := metadataFor(request.ProjectRoot, featurePath, irPath, filePath)
	if err != nil {
		return Metadata{}, err
	}
	if err := writeMetadata(request.OutputDir, featurePath, metadata); err != nil {
		return Metadata{}, err
	}
	return metadata, nil
}

// writeEntryPoint writes the generated acceptance test of one feature and
// returns its path.
func writeEntryPoint(outputDir string, feature runtime.Feature, featurePath, irPath string) (string, error) {
	if err := os.MkdirAll(filepath.Join(outputDir, "metadata"), 0o755); err != nil {
		return "", err
	}
	filePath := filepath.Join(outputDir, stem(irPath)+"_acceptance_test.go")
	if err := os.WriteFile(filePath, []byte(entryPoint(feature, featurePath, irPath)), 0o644); err != nil {
		return "", err
	}
	return filePath, nil
}

// metadataFor describes one generated feature: the entry point's hash and the
// paths the acceptance mutator reads.
func metadataFor(projectRoot, featurePath, irPath, filePath string) (Metadata, error) {
	hash, err := implementationHash(filePath)
	if err != nil {
		return Metadata{}, err
	}
	return Metadata{
		SchemaVersion:      MetadataSchemaVersion,
		FeaturePath:        filepath.ToSlash(featurePath),
		IRPath:             filepath.ToSlash(projectRelative(projectRoot, irPath)),
		ImplementationHash: "sha256:" + hash,
		HashScope:          "generated_files",
		GeneratedFiles:     []string{projectRelative(projectRoot, filePath)},
	}, nil
}

// writeMetadata writes the metadata file the acceptance mutator reads.
func writeMetadata(outputDir, featurePath string, metadata Metadata) error {
	data, err := json.MarshalIndent(metadata, "", "  ")
	if err != nil {
		return err
	}
	metadataPath := filepath.Join(outputDir, "metadata", MetadataName(featurePath))
	return os.WriteFile(metadataPath, append(data, '\n'), 0o644)
}

// MetadataName maps a feature path to its metadata file name: lowercased, with
// every run of non-alphanumeric characters replaced by one hyphen.
func MetadataName(featurePath string) string {
	lowered := strings.ToLower(filepath.ToSlash(featurePath))
	normalized := regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(lowered, "-")
	return strings.Trim(normalized, "-") + ".json"
}

// implementationHash hashes the generated acceptance files only.
func implementationHash(paths ...string) (string, error) {
	sorted := append([]string(nil), paths...)
	sort.Strings(sorted)

	digest := sha256.New()
	for _, path := range sorted {
		data, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		fileSum := sha256.Sum256(data)
		fmt.Fprintf(digest, "%s\n%s\n", filepath.ToSlash(filepath.Base(path)), hex.EncodeToString(fileSum[:]))
	}
	return hex.EncodeToString(digest.Sum(nil)), nil
}

func entryPoint(feature runtime.Feature, featurePath, irPath string) string {
	test := testName(feature.Name)
	// Every generated entry point shares one package, so its constants are
	// named after the feature's test.
	prefix := lowerFirst(strings.TrimPrefix(test, "Test"))
	return fmt.Sprintf(`// Code generated by acceptance-entrypoint-generator. DO NOT EDIT.

package generated

import (
	"os"
	"testing"

	"github.com/unclebob/forgelet-bridge/acceptance/runtime"
	"github.com/unclebob/forgelet-bridge/acceptance/steps"
)

const (
	%sFeaturePath    = %q
	%sDefaultIRPath  = %q
)

func %s(t *testing.T) {
	irPath := os.Getenv(runtime.IRPathEnv)
	if irPath == "" {
		irPath = %sDefaultIRPath
	}
	feature, err := runtime.LoadFeature(irPath)
	if err != nil {
		t.Fatalf("load acceptance IR: %%v", err)
	}
	steps.Registry().Run(t, feature)
}
`, prefix, filepath.ToSlash(featurePath), prefix, filepath.ToSlash(irPath), test, prefix)
}

func lowerFirst(text string) string {
	if text == "" {
		return text
	}
	return strings.ToLower(text[:1]) + text[1:]
}

// testName is the Go test function name of a feature.
func testName(featureName string) string {
	var builder strings.Builder
	builder.WriteString("Test")
	upperNext := true
	for _, char := range featureName {
		switch {
		case char >= 'a' && char <= 'z', char >= 'A' && char <= 'Z', char >= '0' && char <= '9':
			if upperNext {
				builder.WriteString(strings.ToUpper(string(char)))
				upperNext = false
			} else {
				builder.WriteRune(char)
			}
		default:
			upperNext = true
		}
	}
	return builder.String()
}

func stem(path string) string {
	return strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
}

func projectRelative(root, path string) string {
	if root == "" {
		return path
	}
	relative, err := filepath.Rel(root, path)
	if err != nil || strings.HasPrefix(relative, "..") {
		return path
	}
	return relative
}
